export const BOOK_CATEGORIES = [
  "Antika & Koleksiyon Ürünleri",
  "Mimarlık",
  "Sanat",
  "İnciller / Kutsal Kitaplar",
  "Biyografi & Otobiyografi",
  "Beden, Zihin & Ruh",
  "İş & Ekonomi",
  "Çizgi Roman & Grafik Roman",
  "Bilgisayar",
  "Yemek & Mutfak",
  "El Sanatları & Hobiler",
  "Tasarım",
  "Tiyatro / Drama",
  "Eğitim",
  "Aile & İlişkiler",
  "Yabancı Dil Çalışmaları",
  "Oyunlar & Aktiviteler",
  "Bahçecilik",
  "Sağlık & Fitness",
  "Tarih",
  "Ev & Yaşam",
  "Mizah",
  "Dil Bilimleri & Disiplinleri",
  "Hukuk",
  "Edebi Derlemeler",
  "Edebiyat Eleştirisi",
  "Matematik",
  "Tıp",
  "Müzik",
  "Doğa",
  "Sahne Sanatları",
  "Evcil Hayvanlar",
  "Felsefe",
  "Fotoğrafçılık",
  "Şiir",
  "Siyaset Bilimi",
  "Psikoloji",
  "Referans / Başvuru Kitapları",
  "Din",
  "Bilim",
  "Kişisel Gelişim",
  "Sosyal Bilimler",
  "Spor & Rekreasyon",
  "Sınav Hazırlık / Çalışma Kaynakları",
  "Teknoloji & Mühendislik",
  "Ulaşım",
  "Seyahat",
  "Gerçek Suç (True Crime)",
  "Kurgu (Fiction)",
  "Genç Yetişkin Kurgu (Young Adult Fiction)",
  "Çocuk Kurgu (Juvenile Fiction)"
];
